# Generated by Django 6.0.2 on 2026-02-09 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gmail_thread_id', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('RECRUITER_REPLIED', 'Recruiter Replied'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('REJECTED', 'Rejected'), ('OFFER_RECEIVED', 'Offer Received')], default='APPLIED', max_length=30)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('first_detected_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gmail_message_id', models.CharField(max_length=255, unique=True)),
                ('gmail_thread_id', models.CharField(max_length=255)),
                ('subject', models.TextField(blank=True, null=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField()),
                ('processed', models.BooleanField(default=False)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('APPLICATION_DETECTED', 'Application Detected'), ('RECRUITER_REPLY', 'Recruiter Reply'), ('USER_REPLY', 'User Reply'), ('INTERVIEW_INVITE', 'Interview Invite'), ('REJECTION', 'Rejection'), ('OFFER', 'Offer')], max_length=50)),
                ('event_timestamp', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs.jobthread')),
            ],
        ),
        migrations.AddIndex(
            model_name='jobthread',
            index=models.Index(fields=['user'], name='jobs_jobthr_user_id_d56c40_idx'),
        ),
        migrations.AddIndex(
            model_name='jobthread',
            index=models.Index(fields=['status'], name='jobs_jobthr_status_6de75c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobthread',
            index=models.Index(fields=['gmail_thread_id'], name='jobs_jobthr_gmail_t_d7d965_idx'),
        ),
        migrations.AddIndex(
            model_name='jobthread',
            index=models.Index(fields=['last_activity_at'], name='jobs_jobthr_last_ac_bea8d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobthread',
            unique_together={('user', 'gmail_thread_id')},
        ),
        migrations.AddIndex(
            model_name='rawemail',
            index=models.Index(fields=['user'], name='jobs_rawema_user_id_77d6c9_idx'),
        ),
        migrations.AddIndex(
            model_name='rawemail',
            index=models.Index(fields=['gmail_thread_id'], name='jobs_rawema_gmail_t_ca1dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='rawemail',
            index=models.Index(fields=['processed'], name='jobs_rawema_process_0a799c_idx'),
        ),
        migrations.AddIndex(
            model_name='rawemail',
            index=models.Index(fields=['received_at'], name='jobs_rawema_receive_7d5ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='threadevent',
            index=models.Index(fields=['thread'], name='jobs_thread_thread__f51e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='threadevent',
            index=models.Index(fields=['event_type'], name='jobs_thread_event_t_c2c18f_idx'),
        ),
        migrations.AddIndex(
            model_name='threadevent',
            index=models.Index(fields=['event_timestamp'], name='jobs_thread_event_t_85d8d0_idx'),
        ),
    ]
