# Generated by Django 6.0.2 on 2026-02-11 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadevent',
            options={'ordering': ['-event_timestamp']},
        ),
    ]
