# Generated by Django 6.0.2 on 2026-02-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_threadevent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawemail',
            name='body_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
