# Generated by Django 6.0.2 on 2026-02-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rawemail_body_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobthread',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('RECRUITER_REPLIED', 'Recruiter Replied'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('ASSESSMENT_PENDING', 'Assessment Pending'), ('ACTION_REQUIRED', 'Action Required'), ('REJECTED', 'Rejected'), ('OFFER_RECEIVED', 'Offer Received')], default='APPLIED', max_length=30),
        ),
        migrations.AlterField(
            model_name='threadevent',
            name='event_type',
            field=models.CharField(choices=[('APPLICATION_DETECTED', 'Application Detected'), ('RECRUITER_REPLY', 'Recruiter Reply'), ('USER_REPLY', 'User Reply'), ('INTERVIEW_INVITE', 'Interview Invite'), ('ASSESSMENT_REQUESTED', 'Assessment Requested'), ('ACTION_REQUIRED', 'Action Required'), ('REJECTION', 'Rejection'), ('OFFER', 'Offer')], max_length=50),
        ),
    ]
