# Generated by Django 6.0.2 on 2026-02-16 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobthread_status_alter_threadevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rawemail',
            name='classification_source',
            field=models.CharField(default='RULE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='rawemail',
            index=models.Index(fields=['classification'], name='jobs_rawema_classif_217e19_idx'),
        ),
        migrations.AddIndex(
            model_name='rawemail',
            index=models.Index(fields=['classification_source'], name='jobs_rawema_classif_c57ff6_idx'),
        ),
    ]
