# Generated by Django 6.0.2 on 2026-02-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rawemail_classification_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobthread',
            name='followup_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
