# Generated by Django 6.0.2 on 2026-02-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailtoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gmailtoken',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
