# Generated by Django 6.0.2 on 2026-02-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_gmailtoken_is_active_gmailtoken_last_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailtoken',
            name='last_history_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
