# Generated by Django 6.0.2 on 2026-02-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_gmailtoken_last_history_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gmailtoken',
            old_name='last_history_id',
            new_name='gmail_history_id',
        ),
    ]
